Upgrade staging to use Helm v3
jupyterhub/mybinder.org-deploy pull request #1667
Opened 2020-10-23 10:42 UTC by sgibson91

This is a BinderHub version bump. See the link below for a diff of new changes:

https://github.com/jupyterhub/binderhub/compare/<OLD-HASH>...<NEW-HASH>

This is a repo2docker version bump. See the link below for a diff of new changes:

https://github.com/jupyter/repo2docker/compare/<OLD-HASH>...<NEW-HASH>

2020-10-23 10:49 UTC, consideRatio commented
Code is referencing
```
https://storage.googleapis.com/kubernetes-helm/helm-${{ env.HELM_VERSION }}-linux-amd64.tar.gz
```

But while https://storage.googleapis.com/kubernetes-helm/helm-v2.16.10-linux-amd64.tar.gz exist, https://storage.googleapis.com/kubernetes-helm/helm-v3.3.4-linux-amd64.tar.gz doesn't!

2020-10-23 10:50 UTC, consideRatio requested changes
Something must change making it successfully download the v3 version of helm as well.

2020-10-23 10:53 UTC, sgibson91 commented
We can probably revert to these instructions https://helm.sh/docs/intro/install/#from-script

2020-10-23 11:32 UTC, sgibson91 commented
I also need to double check deploy.py

2020-10-23 11:44 UTC, sgibson91 commented
Ok, I just pushed a couple of commits that edit how we double check that we're using the correct version of helm in deploy.py. Could news is I think the could will be more compact once the whole federation is migrated.

2020-10-23 13:27 UTC, consideRatio commented on deploy.py
> +
Is this `--force` for helm 3? Helm 3 force is very destructive I understand it as.

2020-10-23 13:29 UTC, consideRatio approved these changes
I don't spot anything obvious wrong about this, so i think this looks good to me!

2020-10-23 13:42 UTC, sgibson91 commented on deploy.py
> +
No, helm2 which every fed member _except_ staging is running :)

2020-10-23 14:45 UTC, sgibson91 commented
Thanks! I'm about to go out if someone else is able to hit merge and babysit the CI?

2020-10-26 09:18 UTC, sgibson91 commented on deploy.py
> +    if release == "staging":
I'm not sure. The point of this section of the code was to check that the version of helm running locally/on CI matched that on the cluster to avoid getting ourselves into a weird state (like upgrading tiller unknowingly). And now the form of that check looks different depending on which cluster we're logged into. I'm hoping that if this PR goes well, I'll be able to roll through the rest of the federation reasonably quickly.

2020-10-26 09:57 UTC, minrk commented on deploy.py
> +    if release == "staging":
I was thinking it would be a little easier to do the upgrade to say "if we expect helm 3, just check that we get helm 3 and return, otherwise do it the old way." Then it seems easier to delete all the "if not helm 3" branches when we are done upgrading

2020-10-26 10:00 UTC, sgibson91 commented on deploy.py
> +    if release == "staging":
Ah, so move the helm check into main or it's own function?

2020-10-26 10:28 UTC, sgibson91 commented on deploy.py
> +    if release == "staging":
@minrk What do you think of [`cb6e6f8`](https://github.com/jupyterhub/mybinder.org-deploy/pull/1667/commits/cb6e6f816ed5c80baea747a0e0e724ef0be51c8a)?

2020-10-26 10:42 UTC, minrk commented
Looks great! Feel free to merge when you feel like you have a little bit of time to watch the CI do its thing.

2020-10-26 10:42 UTC, minrk commented on deploy.py
> +    if release == "staging":
👍

2020-10-26 10:42 UTC, minrk approved these changes

2020-10-26 11:34 UTC, merged