WIP: EKS in AWS Curvenote account
jupyterhub/mybinder.org-deploy pull request #2652
Opened 2023-06-01 21:46 UTC by manics

Very much a work in progress, but this is enough to deploy a basic EKS cluster.
- [ ] OIDC (IRSA and GitHub OIDC)
- [ ] Deploy BinderHub manually
- [ ] Add docs
- [ ] Deploy BinderHub via CI

Related to
- https://github.com/jupyterhub/mybinder.org-deploy/issues/2556
- https://github.com/jupyterhub/team-compass/issues/501

2023-06-30 19:43 UTC, manics commented on .github/workflows/aws-dev.yml
> +# This is a temporary workflow to check whether AWS OIDC EKS access is working
I'll delete workflow this in a follow-up PR where I add the binderhub deployment

2023-06-30 19:45 UTC, manics commented on .pre-commit-config-terraform.yaml
> +files: "^terraform/aws/curvenote/"
I think we should run as many static checks as possible on our terraform code since we can't really test them, though we can discuss that later. For now I've limited it to the new AWS Curvenote terraform.

2023-06-30 21:27 UTC, manics commented on .github/workflows/aws-dev.yml
> +# This is a temporary workflow to check whether AWS OIDC EKS access is working
.... though it's intermittently broken at the moment due to a change in certificates
https://github.blog/changelog/2023-06-27-github-actions-update-on-oidc-integration-with-aws/

This is configured in the private AWS config repo since it requires elevated account privileges.

2023-06-30 21:32 UTC, manics commented
This is ready for review! This is just the Terraform for deploying the EKS cluster on Curvenote's AWS account. Instructions are in the README.

I've deployed a limited BinderHub to https://3.13.147.101.nip.io/
Since this is just for testing:
- maximum pod lifetime in the idle culler is set to 15 minutes though it doesn't always work due to https://github.com/jupyterhub/mybinder.org-deploy/issues/2686
- I've deployed an ECR registry cleaner which deletes images that haven't been pulled after ~1 day
- Single node

I'll open a separate PR for the Helm chart deployment.

2023-07-10 21:21 UTC, manics commented
I've pushed some changes so some (but not all) Terraform changes can be automatically deployed by GitHub workflow in future. For example, I think K8s upgrades and changes to node sizes/numbers can be deployed without manual intervention.

This requires some repo changes:
- `TFPLAN_ARTIFACT_PASSPHRASE` secret
- `aws-curvenote` environment with branch restriction and required reviewers for deployments
 
See the `## Automatic deployment (GitHub workflows)` section of the README file included here for details.

If everyone's happy with this plan I'll make the relevant changes in the mybinder.org-deploy repo settings before his is merged.

2023-07-10 21:23 UTC, manics commented on .github/workflows/aws-dev.yml
> +# This is a temporary workflow to check whether AWS OIDC EKS access is working
Now fixed forever (hopefully) since AWS added a workaround to avoid the dependence on GitHub's intermediate certificates https://github.com/aws-actions/configure-aws-credentials/issues/357#issuecomment-1626357333

2023-07-31 22:49 UTC, manics commented
I've added some screenshots of the deployment workflow to the `terraform/aws/curvenote/README`: https://github.com/manics/mybinder.org-deploy/blob/aws-curvenote/terraform/aws/curvenote/README.md

2023-08-08 00:39 UTC, yuvipanda reviewed
Thank you so much for working on this, @manics. I've left some comments inside.

I think two overarching questions for me.

1. I have so far not trusted `terraform plan` to run on CI, anywhere. In general, I always recommend humans run it manually and type the 'yes', after making a PR with proposed changes. I've personally accidentally run terraform apply that has deleted entire clusters, user data, etc and had to ctrl-c them - things that went past review by others of both the code and the plan. Due to the intense destruction possible, I've never trusted it to auto run on CI. I'm not opposed to it here because you've already done all the hard work (the github oidc stuff is pretty cool!), but just wanted to ask if you're open to not having terraform apply be run on CI?
2. I don't think a lot of this is curvenote specific - is a curvenote directory with `.tf` files fully necessary? Can they not be just a `.tfvars` file? I am trying to understand what makes it special vs any other AWS setup we might have in the future. 
3. I left another comment inline about the eks module.

In general, I think it's alright to merge this with minor modifications and then evolve this over time.

Thank you so much for working on this!

2023-08-08 00:39 UTC, yuvipanda commented on .github/workflows/terraform-deploy-aws-curvenote.yml
> +      - aws-curvenote2
I'm guessing this would need to be removed before merge?

2023-08-08 00:39 UTC, yuvipanda commented on .github/workflows/terraform-deploy-aws-curvenote.yml
> +          echo ${{ secrets.TFPLAN_ARTIFACT_PASSPHRASE }} | gpg --batch --yes --passphrase-fd 0 --decrypt --cipher-algo AES256 --output "${TFPLAN}" "${TFPLAN}.gpg"
Can we use anything other than gpg? [age](https://github.com/FiloSottile/age) perhaps?

2023-08-08 00:39 UTC, yuvipanda commented on terraform/aws/curvenote/README.md
> +in [`provider.tf`](provider.tf) to use a different key and/or bucket.
I would love for us to just use s3 or gcs as the backend from the very start, and just not use filesystem based lock files at all. I am worried about corruption, and rollbacks being hard if the terraform state is lost when it's applied on GH Actions - the plan succeeds but the apply fails (has happened to me many times).

So the concrete suggestion here is to not use local state files at all, and just start off on s3 or gcs.

2023-08-08 00:39 UTC, yuvipanda commented on terraform/aws/curvenote/bootstrap/backend.tf
> +  # python -c 'import random; import string; print("".join(random.choices(string.ascii_lowercase + string.digits,k=12)))'
I'd suggest `pwgen -1 12` instead?

2023-08-08 00:39 UTC, yuvipanda commented on terraform/aws/curvenote/bootstrap/backend.tf
> +variable "bucket-name" {
Maybe call this `state_bucket_name`?

2023-08-08 00:39 UTC, yuvipanda commented on terraform/aws/curvenote/bootstrap/backend.tf
> +      sse_algorithm = "AES256"
Do we need to specify this? I thought it's on by default now https://aws.amazon.com/blogs/aws/amazon-s3-encrypts-new-objects-by-default/

2023-08-08 00:39 UTC, yuvipanda commented on terraform/aws/curvenote/eks-cluster.tf
> +    worker_group-1 = {
Let's stick to just using `_` or just using `-`? I'd prefer just using `_`

2023-08-08 00:39 UTC, yuvipanda commented on terraform/aws/curvenote/eks-cluster.tf
> +module "eks" {
I don't want to block this PR on this as it's a significant change, but just a few weeks ago I had to rip out this particular eks module out of terraform I maintain for pangeo-forge - https://github.com/yuvipanda/pangeo-forge-cloud-federation/pull/4. Ongoing maintanence was difficult and quite buggy unfortunately.

I'm ok with us giving it a try here, but given how simple the pangeo-forge env was I'm a little sad this module didn't work out.

2023-08-08 00:39 UTC, yuvipanda commented on terraform/aws/curvenote/k8s-access.tf
> +              # GitHub repositories and refs allowed to use this role
this is pretty cool!

2023-08-08 00:39 UTC, yuvipanda commented on terraform/aws/curvenote/outputs.tf
> +# output "cluster_name" {
Should this be uncommented or removed from the PR?

2023-08-28 22:44 UTC, manics commented on .github/workflows/terraform-deploy-aws-curvenote.yml
> +      - aws-curvenote2
Yes, I'm using it to test the continuous deployment process on my fork. I'll remove it just before merging (or in a follow-up PR).

2023-08-28 22:48 UTC, manics commented on .github/workflows/terraform-deploy-aws-curvenote.yml
> +          echo ${{ secrets.TFPLAN_ARTIFACT_PASSPHRASE }} | gpg --batch --yes --passphrase-fd 0 --decrypt --cipher-algo AES256 --output "${TFPLAN}" "${TFPLAN}.gpg"
I'm using gpg because it's pre-installed in the base environment. This is purely for internal GH workflow use- there's no way to privately pass an artefact between separate jobs, and since this is a public repo it needs to be encrypted. It's not intended to be used by people/maintainers since if we need the full details we can run Terraform anyway, it's just a way to ensure the public can't view any sensitive information in the plan. My plan is to create a random GitHub secret `TFPLAN_ARTIFACT_PASSPHRASE` and then throw it away so we'll never know the secret.

2023-08-28 22:49 UTC, manics commented on terraform/aws/curvenote/README.md
> +in [`provider.tf`](provider.tf) to use a different key and/or bucket.
This is part of the setup/bootstrapping stage- you need to create and configure the S3 bucket/prefix and DynamoDB table before you can use it!

2023-08-28 22:50 UTC, manics commented on terraform/aws/curvenote/bootstrap/backend.tf
> +  # python -c 'import random; import string; print("".join(random.choices(string.ascii_lowercase + string.digits,k=12)))'
Maybe- though `pwgen` isn't installed on my system, whereas Python is almost guaranteed to be installed on mybinder maintainers' systems.

2023-08-28 22:53 UTC, manics commented on terraform/aws/curvenote/bootstrap/backend.tf
> +      sse_algorithm = "AES256"
Does that apply to the bucket's default policy, or only to the S3 upload API call?

2023-08-28 22:53 UTC, manics commented on terraform/aws/curvenote/eks-cluster.tf
> +module "eks" {
It's been working fine for me, I've used it for a few clusters now. What problems did you run into?

2023-08-28 23:04 UTC, manics commented
> I have so far not trusted terraform plan to run on CI, anywhere. In general, I always recommend humans run it manually and type the 'yes', after making a PR with proposed changes. I've personally accidentally run terraform apply that has deleted entire clusters, user data, etc and had to ctrl-c them - things that went past review by others of both the code and the plan. Due to the intense destruction possible, I've never trusted it to auto run on CI. I'm not opposed to it here because you've already done all the hard work (the github oidc stuff is pretty cool!), but just wanted to ask if you're open to not having terraform apply be run on CI?

You're right that it's a potentially very destructive action, but the same applies to Helm or any other continuous deployment process. In practice I've seen many more errors, near-misses, and other problems due to relying on manual terraform deployments in a team environment. Things like using the wrong AWS account profile, mixing up dev and prod, deploying the wrong repo, using the wrong branch, having an out-of-date branch, forgetting to push commits, pushing commits but not deploying, closing a laptop in the middle of a long running deployment leading to a corrupt state file, etc. The two step GitHub job with environment requiring manual approval can be setup to notify particular named users of a pending plan. It's not as good as a full hosted application for managing Terraform deployments, but I think it's good enough given the constraints of a public GitHub repo.

> I don't think a lot of this is curvenote specific - is a curvenote directory with .tf files fully necessary? Can they not be just a .tfvars file? I am trying to understand what makes it special vs any other AWS setup we might have in the future.

Good point. I've moved it into a module `binder-eks` instead of relying on tfvars files. The benefit of the module is you can just do `cd <deployment>; terraform apply` for each deployment as with all the other clouds. Using variables would require `terraform apply -var-file=<deployment>.tfvars` which is more error prone.

2023-08-29 01:24 UTC, yuvipanda commented on terraform/aws/curvenote/eks-cluster.tf
> +module "eks" {
@manics https://github.com/yuvipanda/pangeo-forge-cloud-federation/issues/3 was the problem when I tried to use it in pangeo-forge, and I couldn't debug what was going on after a few hours. Eventually I just had to tear it all down and rebuild it without the module. It was a similar setup with the 2i2c infra (where we are still using eksctl directly)

2023-09-18 14:47 UTC, manics commented on .github/workflows/terraform-deploy-aws-curvenote.yml
> +      - aws-curvenote2
```suggestion
```

2023-09-18 19:12 UTC, yuvipanda commented
I will schedule some time for wednesday / thursday to give this another thorough looking over! Hopefully merge soon. One comment before that is:

> Good point. I've moved it into a module binder-eks instead of relying on tfvars files. The benefit of the module is you can just do cd <deployment>; terraform apply for each deployment as with all the other clouds. Using variables would require terraform apply -var-file=<deployment>.tfvars which is more error prone.

To me, the `.tfvars` are useful when you need to have many instances. So when we have another AWS binder, we could just add another `.tfvars` file rather than copy paste a whole directory. Could we not deal with the possible errors of not passing `-var-file` by making variables as required instead?

2023-09-18 19:45 UTC, yuvipanda commented on .github/workflows/terraform-deploy-aws-curvenote.yml
> +          echo ${{ secrets.TFPLAN_ARTIFACT_PASSPHRASE }} | gpg --batch --yes --passphrase-fd 0 --decrypt --cipher-algo AES256 --output "${TFPLAN}" "${TFPLAN}.gpg"
I'd still love to get rid of it. I basically can't trust myself to ever verify if a GPG commandline is actually doing what it is supposed to do. `age` can come from apt here, and we can just use it to symmetrically encrypt / decrypt. then:

1. Make an private age key with `age-keygen -o <some-file>`. The file is just one line, we put it into a GitHub secret
2. When we wanna encrypt, `echo $KEY > <some-file>; age --identity <some-file> --encrypt --output <encrypted-output-file> <unencrypted-input-file>`. We can also pass in input via stdin.
3. And to decrypt, do it in reverse: `echo $KEY > <some-file>; age --identity <some-file> --decrypt --output <unencrypted-output-file> <encrypted-input-file>`. The input can come via stdin too.

IMO this is much simpler to understand and verify, and given there's already a lot of complexity here I'd love to not touch GPG at all.

2023-09-19 15:11 UTC, manics commented on .github/workflows/terraform-deploy-aws-curvenote.yml
> +          echo ${{ secrets.TFPLAN_ARTIFACT_PASSPHRASE }} | gpg --batch --yes --passphrase-fd 0 --decrypt --cipher-algo AES256 --output "${TFPLAN}" "${TFPLAN}.gpg"
OK, I'll see if I can get that to work.

2023-09-19 15:12 UTC, manics commented
> So when we have another AWS binder, we could just add another .tfvars file rather than copy paste a whole directory.

This is a module, so you just reference it as a path, you don't need to copy anything:
https://github.com/manics/mybinder.org-deploy/blob/8c1cfb1c9080a0c325a90f7cac113faa88aa519f/terraform/aws/curvenote/main.tf#L35

2023-09-19 16:12 UTC, minrk commented on terraform/aws/curvenote/.terraform.lock.hcl
probably don't want to commit the lock, right?

2023-09-19 17:55 UTC, minrk commented on terraform/aws/curvenote/.terraform.lock.hcl
resolved in meeting that this _is_ something we want to do.

2023-09-21 17:40 UTC, yuvipanda requested changes
Some super minor changes requested, but the primary one would be to replace `gpg` with `age`. After that I think this is good to go! 

I'm still somewhat skeptical of the EKS module, but only because I *really* want it to work and have been burnt by that in the past. However, this is generally a fast moving space anyway, and I hope this does work. Let's try it out!

Thank you so much, @manics!

2023-09-21 17:40 UTC, yuvipanda commented on terraform/aws/binder-eks/k8s-access.tf
> +              "repo:jupyterhub/mybinder.org-deploy:ref:refs/heads/main",
This is pretty cool I must say :)

2023-09-21 17:40 UTC, yuvipanda commented on terraform/aws/binder-eks/k8s-access.tf
> +              "repo:manics/mybinder.org-deploy:ref:refs/heads/aws-curvenote",
Just a reminder to get rid of this before merging.

2023-09-21 17:40 UTC, yuvipanda commented on terraform/aws/binder-eks/k8s-access.tf
> +              # TODO: Remove this, just for development:
Reminder

2023-09-21 17:40 UTC, yuvipanda commented on terraform/aws/binder-eks/vpc.tf
> +  # azs                  = data.aws_availability_zones.available.names[:1]
Let's get rid of this commented out line, or use it?

2023-09-21 17:40 UTC, yuvipanda commented on terraform/aws/curvenote/bootstrap/backend.tf
> +  # python -c 'import random; import string; print("".join(random.choices(string.ascii_lowercase + string.digits,k=12)))'
I was trying to figure out if we should use the `secrets` module instead, given that `random` is a PRNG and shouldn't be used for 'security' purposes. However, this is not being used in any cryptographic manner, just as a way to avoid clashes - so is fine.

2023-09-21 17:40 UTC, yuvipanda commented on terraform/aws/curvenote/bootstrap/backend.tf
> +      sse_algorithm = "AES256"
Pretty sure it applies to the default policy. Can be verified by taking this out and looking in the AWS console to see if this has changed?

2023-09-22 17:11 UTC, yuvipanda approved these changes
Thanks a lot, @manics! I think this is ready to merge! I've marked it as approved, so you should merge whenever you feel convenient.

EXCITED TO SEE THIS WORK!

2023-09-24 20:16 UTC, manics commented
@yuvipanda Thanks for working through this! I've pushed a couple more minor changes, if no-one else has comments I'll setup the GitHub secret and environment tomorrow and merge.

2023-09-25 21:31 UTC, manics commented
I've created the secret `TFPLAN_ARTIFACT_SECRET_KEY`
and the Environment:
![image](https://github.com/jupyterhub/mybinder.org-deploy/assets/1644105/0dc1df98-022b-43df-a38a-045e7bb5f9db)
So far I've only added myself to be notified when there is a pending terraform change, but I think we should change that to a GitHub team- to be followed up.

2023-09-25 21:31 UTC, merged